require(game.Players.LocalPlayer.PlayerGui.MainUI.Initiator.Main_Game).caption("Mode Has Shutdown, Sorry You",true)
wait(2.6)
require(game.Players.LocalPlayer.PlayerGui.MainUI.Initiator.Main_Game).caption("You can test new mode ",true)
wait(1)
setclipboard("loadstring(game:HttpGet('https://pastefy.app/YAx1dSmY/raw'))() ")
